replicaCount: 1

mysql:
  databaseName: currencyExchange

springApp:
  image:
    repository: taregsafi/jenkins-ci-cd
    pullPolicy: IfNotPresent
    tag: latest

mysqlVolume:
  persistentVolumeClaim:
    storageSize: 500Mi

  persistentVolume:
    storageSize: 500Mi
    pathOnHost: /var/lib/mysql

  mountPath: /var/lib/mysql
