apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ci-cd-deployment
  labels:
    app: jenkins-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ci-cd
  template:
    metadata:
      labels:
        app: jenkins-ci-cd
    spec:
      containers:
        - name: jenkins-ci-cd
          image: taregsafi/jenkins-ci-cd:latest
          ports:
            - containerPort: 7070
