apiVersion: v1
kind: Service
metadata:
  name: jenkins-ci-cd
spec:
  type: NodePort
  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 30007 # NodePort range is 30000-32767
  selector:
    app: jenkins-ci-cd
