apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
          - name: mysql
            image: mysql:latest
            ports:
              - containerPort: 3306
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql-root-password
                    key: password
              - name: MYSQL_DATABASE
                value: {{ .Values.mysql.databaseName }}
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mysql-password
                    key: password
            volumeMounts:
              - name: mysql-storage
                mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
