apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-app-service
spec:
  selector:
    app: {{ .Release.Name }}-spring-app
  ports:
      - protocol: TCP
        port: 7070
        targetPort: 7070
  type: LoadBalancer
